name: mapbox_search_flutter
description: This package provides some helper widgets to use with mapbox_search library.
version: 1.0.6
authors:
  - Ketan Choyal <ketanchoyal@gmail.com>
  - Daniel Oliveira <shinayser@gmail.com>
homepage: https://github.com/ketanchoyal/mapbox_search_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_search: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
